<?php

namespace Soar\Csv;

use Illuminate\Support\ServiceProvider;

class CsvServiceProvider extends ServiceProvider
{
    protected $defer= true;

    /**
     * Register services.
     *
     * @return void
     */
    public function register()
    {
        $this->app->singleton('csv', function ($app) {
            return new Csv($app['session'], $app['config']);
        });
    }

    /**
     * Bootstrap services.
     *
     * @return void
     */
    public function boot()
    {
        // 发布
        $this->publishes(
            [
                __DIR__ . '/config/csv.php' => config_path('csv.php'),
            ]
        );
    }

    public function provides()
    {
        return ['csv'];
//        return parent::provides(); // TODO: Change the autogenerated stub
    }
}
